### ISSUE TITLE
Gameboy colour games not working

### ISSUE THREAD

**Issue by Breadmasterpro** [deltabeard/Peanut-GB#113]
They show an error. Even changing the palette does nothing.
![20241004_190108](https://github.com/user-attachments/assets/6c47faf9-f081-4dbf-82f6-0283a56e6f22)
![20241004_190044](https://github.com/user-attachments/assets/ac46481d-adb5-4028-bc06-42581926fd14)

**Comment by Breadmasterpro** [comment]
And half of the games on my sd card do not show up.

**Comment by deltabeard** [comment]
Peanut-GB only supports Game Boy (DMG) games, not Game Boy Color (CGB). This is mentioned in the Readme file at https://github.com/deltabeard/Peanut-GB/blob/66f795935c7212c7dcfda9b5ad018a284db0350f/README.md?plain=1#L12

The other games on your SD card probably don't show up because they end with ".gbc" which are not supported with Peanut-GB.

You are running a program that uses Peanut-GB. What is the name of the program you are running and where did you download it?

**Comment by dogtopus** [comment]
You can use the WIP (but now slightly outdated) `cgb` branch to run GBC games.

**Comment by Breadmasterpro** [comment]
> Peanut-GB only supports Game Boy (DMG) games, not Game Boy Color (CGB). This is mentioned in the Readme file at
> 
> https://github.com/deltabeard/Peanut-GB/blob/66f795935c7212c7dcfda9b5ad018a284db0350f/README.md?plain=1#L12
> 
> The other games on your SD card probably don't show up because they end with ".gbc" which are not supported with Peanut-GB.
> 
> You are running a program that uses Peanut-GB. What is the name of the program you are running and where did you download it?

I use this firmware [https://github.com/Mr-PauI/Gameboy-Enhanced-Firmware-m5stack-cardputer-](url)

**Comment by deltabeard** [comment]
I'm closing the issue because CGB isn't officially supported by Peanut-GB yet. I want to focus on fixing issues with DMG games first. There is preliminary support in the `cgb` branch. You can enquire as to CGB support on the m5stack at the repo where you downloaded the firmware at https://github.com/Mr-PauI/Gameboy-Enhanced-Firmware-m5stack-cardputer-, but unfortunately, opening issues on that repo is disabled (why @Mr-PauI?).

**Comment by Mr-PauI** [comment]
There is no reason except that I haven't enabled it and I guess that's something you have to manually turn on(issue reporting). I have been using _gameboyenhancedfirmware@gmail.com_ for bug reports and support. The project is built with the primary Peanut-GB project core, not the CGB branch. It only lists the ROMs because some are backwards compatible titles. If I release a variant based on the CGB branch, it will be a separate project. I've edited the main page to make the support email address more visible, as well as the other methods of contacting me.

**Comment by Breadmasterpro** [comment]
> There is no reason except that I haven't enabled it and I guess that's something you have to manually turn on(issue reporting). I have been using _[gameboyenhancedfirmware@gmail.com](mailto:gameboyenhancedfirmware@gmail.com)_ for bug reports and support. The project is built with the primary Peanut-GB project core, not the CGB branch. It only lists the ROMs because some are backwards compatible titles. If I release a variant based on the CGB branch, it will be a separate project. I've edited the main page to make the support email address more visible, as well as the other methods of contacting me.

@Mr-PauI so .gbc files do not work, correct?

**Comment by Mr-PauI** [comment]
@Breadmasterpro Only a selection of titles that are backwards compatible with the original system. 
For example: Pokemon Silver/Gold, Dragon Warrior I&II and Azure dreams.

If you have questions, you can email the address I gave above, start a thread under r/CardPuter or reach me on the cardputer discord channel. If there is a title compatible with another Peanut-GB based emulator implementation, I certainly want to know about that. My goal has been to achieve parity with a PC implementation in terms of compatibility, which has been established afaik.

**Comment by Breadmasterpro** [comment]
> @Breadmasterpro Only a selection of titles that are backwards compatible with the original system. For example: Pokemon Silver/Gold, Dragon Warrior I&II and Azure dreams. There is limited colour support for the Pokemon titles Silver/Gold and Dragon Warrior features its super gameboy palette.
> 
> If you have questions, you can email the address I gave above, start a thread under r/CardPuter or reach me on the cardputer discord channel. If there is a title compatible with another Peanut-GB based emulator implementation, I certainly want to know about that. My goal has been to achieve parity with a PC implementation in terms of compatibility, which has been established afaik.

thankyou
