### ISSUE TITLE
no input possible on certain roms

### ISSUE THREAD

**Issue by itsmeitsme** [deltabeard/Peanut-GB#38]
Hi, 

I've ported this emulator to a ESP32 based embedded system.
While the main functions work fine, I'm having some trouble with keypad inputs.

Super Mario Land: input works fine
Tetris: no input possible
this is where I got my roms: [Edit: Removed]

**Comment by deltabeard** [comment]
Hi,

According to issue https://github.com/deltabeard/Peanut-GB/issues/31 Tetris has a problem whereby you can't get past the start screen. This is due to poor emulation accuracy of Peanut-GB unfortunately (and also poor programming within that game?).
Tetris 2, Tetris DX and Tetris Plus are tested working however.

Please do not link to ROM downloading websites. Instead, acquire your ROMs legally by reading  them off of physical cartridges that you own.

Thanks. Good luck with your ESP32 project. :+1:

**Comment by deltabeard** [comment]
Tetris is now working as of commit cd1474d3b0866900f16df8610b4f9be5e5d65b67
