### ISSUE TITLE
Main sprite disappears in some games

### ISSUE THREAD

**Issue by YouMakeTech** [deltabeard/Peanut-GB#69]
Sometimes, in some (of my favorite :-)) games (e.g. Metroid II and Batman The Animated Series), the main sprite disappears. 
Please see example of the beginning of Metroid II, right at the beginning after the main menu:
![Screenshot from 2022-12-11 08-27-32](https://user-images.githubusercontent.com/17646734/206891547-78800bb7-41df-4826-9de8-a77a97306e2e.png)

**Comment by deltabeard** [comment]
I think I've fixed the issue in commit 878bc90a9766cfef5cb57ba64b8a0269a20bc326. Please check.

![METROID2](https://user-images.githubusercontent.com/3747104/206912284-d3a22bb2-187f-4b4b-b99d-65dfc4bd3094.gif)

The background draws over the sprite when required, making it look like Samus is walking behind the bush as shown in the animation above.
The extra logic required to get this working will have some impact on LCD drawing performance though.

**Comment by YouMakeTech** [comment]
I'll check today. You're awesome. Thanks!

**Comment by YouMakeTech** [comment]
Thanks Mahyar, it works great. No noticeable change in performance

**Comment by deltabeard** [comment]
The changes made seem to introduce some drawing errors in other games now. In certain instances, the sprites will appear miscoloured or overlayed incorrectly. For example, in Super Mario Land 2 when Mario is going into a pipe, the sprite appears inverted colours:

![MARIOLAND2_0000000015](https://user-images.githubusercontent.com/3747104/207971215-c61c31aa-0989-4295-b25f-056ce2884c8d.png)

The Jigglypuff in the opening animation in Pokemon R/B is incorrectly overlayed on Gengar on some frames.
![POKEMON BLUE.webm](https://user-images.githubusercontent.com/3747104/207971079-834fffda-0f60-470e-8a04-a3b8db764d67.webm)

I'll reopen this issue so that I can find a better resolution than the current fix.

**Comment by deltabeard** [comment]
The issue should be fixed properly now. Before, it was assumed that color 0 of the BG palette was transparent, but in some games like Metroid, colour 0 is black, and instead colour 3 is white.
