### ISSUE TITLE
Adventure Island wrong sprites rendering issue

### ISSUE THREAD

**Issue by ESPboy-edu** [deltabeard/Peanut-GB#78]
Last release was used.
Wrong ingame background and sprites rendering

**Comment by deltabeard** [comment]
This issue seems to be fixed on the ppu-fix branch with commit fcb42682129243e34e6446eadb5e654778b35933.

![ADVENTURE_ISLAND](https://user-images.githubusercontent.com/3747104/230724718-76756456-2b44-4d2b-b910-2cbfa3ded626.gif)

Let me know if the fix doesn't work, or if this causes other games that used to work to not do so anymore. I'll merge the branch into master after testing a few more games.
